### ISSUE TITLE
puppeteer: MaxListenersExceededWarning

### ISSUE THREAD

**Issue by dennismuench** [ycmjason/svg-to-img#2] opened 2018-11-19 22:10 UTC
Hi,

the following is a warning arising from puppeteer after the successful creation of the image. The issue itself is most probably a puppeteer issue but since there will more warnings and info messages like this in the future in a package that big (271 issues) it would be nice to suppress warnings from puppeteer as it is a bit distracting within a console application. Would that be possible?

```
(node:7292) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:280:19)
    at process.addListener (events.js:297:10)
    at Function.addEventListener (E:\***\node_modules\puppeteer\lib\helper.js:165:13)
    at Launcher.launch (E:\***\node_modules\puppeteer\lib\Launcher.js:155:32)
    at <anonymous>
(node:7292) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:280:19)
    at process.addListener (events.js:297:10)
    at Function.addEventListener (E:\***\node_modules\puppeteer\lib\helper.js:165:13)
    at Launcher.launch (E:\***\node_modules\puppeteer\lib\Launcher.js:157:29)
    at <anonymous>
(node:7292) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:280:19)
    at process.addListener (events.js:297:10)
    at Function.addEventListener (E:\***\node_modules\puppeteer\lib\helper.js:165:13)
    at Launcher.launch (E:\***\node_modules\puppeteer\lib\Launcher.js:159:29)
    at <anonymous>
(node:7292) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:280:19)
    at process.addListener (events.js:297:10)
    at Function.addEventListener (E:\***\node_modules\puppeteer\lib\helper.js:165:13)
    at Launcher.launch (E:\***\node_modules\puppeteer\lib\Launcher.js:161:29)
    at <anonymous>
```

**Comment by dennismuench** [comment] 2018-11-19 23:13
Might be as well a problem within this package. The issue arises when used to create alot of images in parallel using the One-off API. Explicitly calling `page.removeAllListeners()` might solve that...

https://github.com/GoogleChrome/puppeteer/issues/1981
https://github.com/GoogleChrome/puppeteer/issues/594

**Comment by ycmjason** [comment] 2018-11-21 13:03
Thanks for reporting this. Let me have a look at it tonight. Meanwhile is there any step/code which I could follow to recreate the issue? Thanks.

**Comment by dennismuench** [comment] 2018-11-21 17:12
Thanks for your fast response. There you go!
```javascript
const SvgToImg = require('@ycm.jason/svg-to-img');

const promises = [];

// if you set len to 10, everything works just fine
// if you set len to 30, MaxListenersExceededWarning occurs

for (var i = 0, len = 10; i < len; i += 1) {
    promises.push(SvgToImg.png(`<?xml version="1.0" encoding="utf-8"?>
<!-- Svg Vector Icons : http://www.onlinewebfonts.com/icon -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1000 1000" enable-background="new 0 0 1000 1000" xml:space="preserve">
<metadata> Svg Vector Icons : http://www.onlinewebfonts.com/icon </metadata>
<g><path d="M500,10C229.4,10,10,229.4,10,500c0,270.6,219.4,490,490,490c270.6,0,490-219.4,490-490C990,229.4,770.6,10,500,10L500,10z M799,799c-38.8,38.9-84.1,69.3-134.4,90.6c-52.1,22-107.4,33.2-164.6,33.2c-57.1,0-112.5-11.2-164.6-33.2c-50.3-21.3-95.6-51.8-134.4-90.6c-38.9-38.8-69.3-84.1-90.6-134.4c-22-52.1-33.2-107.4-33.2-164.6c0-57.1,11.2-112.5,33.2-164.6c21.3-50.3,51.8-95.6,90.6-134.4c38.9-38.9,84.1-69.3,134.4-90.6c52.1-22,107.4-33.2,164.6-33.2c57.1,0,112.5,11.2,164.6,33.2c50.3,21.3,95.6,51.8,134.4,90.6c38.8,38.9,69.3,84.1,90.6,134.4c22,52.1,33.2,107.4,33.2,164.6c0,57.1-11.2,112.5-33.2,164.6C868.3,714.9,837.8,760.1,799,799L799,799z M727.6,315.4L426.9,616.2L297,486.3c-12.6-12.6-33-12.6-45.6,0c-12.6,12.6-12.6,33,0,45.6l152.6,152.6c12.6,12.6,33,12.6,45.6,0L773.2,361c12.6-12.6,12.6-33,0-45.6C760.6,302.8,740.2,302.8,727.6,315.4L727.6,315.4z"/></g>
</svg>
    `));
}

Promise.all(promises).then(() => {
    console.log('Rendered', promises.length, 'images');
}).catch((err) => {
    console.error(err);
});
```

**Comment by ycmjason** [comment] 2018-11-23 15:45
Hi @dennismuench,

Thank you so much again for reporting this. I am really glad to see people using my library.

After inspecting the issue, a fix for the issue is to do `process.setMaxListeners(n)`, where `n` is a large number or `Infinity`. However, I think this line should be done by the user. So that we don't add side effect to the whole process.

A better fix for this is to use the [Persistent API](https://github.com/ycmjason/svg-to-img#persistent-api). The persistent API is designed to do multiple rendering. It will be much more memory efficient because all rendering will be done in a single instance of puppeteer. In contrast, the one-off api will spawn an instance of puppeteer for each rendering.

Transforming your example to persistent api:
```js
const svgToImg = require('@ycm.jason/svg-to-img')();

const promises = [];

for (var i = 0, len = 30; i < len; i += 1) {
  promises.push(svgToImg.png(`<?xml version="1.0" encoding="utf-8"?>
<!-- Svg Vector Icons : http://www.onlinewebfonts.com/icon -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1000 1000" enable-background="new 0 0 1000 1000" xml:space="preserve">
<metadata> Svg Vector Icons : http://www.onlinewebfonts.com/icon </metadata>
<g><path d="M500,10C229.4,10,10,229.4,10,500c0,270.6,219.4,490,490,490c270.6,0,490-219.4,490-490C990,229.4,770.6,10,500,10L500,10z M799,799c-38.8,38.9-84.1,69.3-134.4,90.6c-52.1,22-107.4,33.2-164.6,33.2c-57.1,0-112.5-11.2-164.6-33.2c-50.3-21.3-95.6-51.8-134.4-90.6c-38.9-38.8-69.3-84.1-90.6-134.4c-22-52.1-33.2-107.4-33.2-164.6c0-57.1,11.2-112.5,33.2-164.6c21.3-50.3,51.8-95.6,90.6-134.4c38.9-38.9,84.1-69.3,134.4-90.6c52.1-22,107.4-33.2,164.6-33.2c57.1,0,112.5,11.2,164.6,33.2c50.3,21.3,95.6,51.8,134.4,90.6c38.8,38.9,69.3,84.1,90.6,134.4c22,52.1,33.2,107.4,33.2,164.6c0,57.1-11.2,112.5-33.2,164.6C868.3,714.9,837.8,760.1,799,799L799,799z M727.6,315.4L426.9,616.2L297,486.3c-12.6-12.6-33-12.6-45.6,0c-12.6,12.6-12.6,33,0,45.6l152.6,152.6c12.6,12.6,33,12.6,45.6,0L773.2,361c12.6-12.6,12.6-33,0-45.6C760.6,302.8,740.2,302.8,727.6,315.4L727.6,315.4z"/></g>
</svg>
    `));
}

Promise.all(promises).then(() => {
  svgToImg.close();
  console.log('Rendered', promises.length, 'images');
}).catch((err) => {
  console.error(err);
});
```

Or if for whatever reason you insist using the one-off api, you could consider doing this:
```js
const SvgToImg = require('@ycm.jason/svg-to-img');

const promises = [];

process.setMaxListeners(Infinity);

for (var i = 0, len = 30; i < len; i += 1) {
  promises.push(SvgToImg.png(`<?xml version="1.0" encoding="utf-8"?>
<!-- Svg Vector Icons : http://www.onlinewebfonts.com/icon -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1000 1000" enable-background="new 0 0 1000 1000" xml:space="preserve">
<metadata> Svg Vector Icons : http://www.onlinewebfonts.com/icon </metadata>
<g><path d="M500,10C229.4,10,10,229.4,10,500c0,270.6,219.4,490,490,490c270.6,0,490-219.4,490-490C990,229.4,770.6,10,500,10L500,10z M799,799c-38.8,38.9-84.1,69.3-134.4,90.6c-52.1,22-107.4,33.2-164.6,33.2c-57.1,0-112.5-11.2-164.6-33.2c-50.3-21.3-95.6-51.8-134.4-90.6c-38.9-38.8-69.3-84.1-90.6-134.4c-22-52.1-33.2-107.4-33.2-164.6c0-57.1,11.2-112.5,33.2-164.6c21.3-50.3,51.8-95.6,90.6-134.4c38.9-38.9,84.1-69.3,134.4-90.6c52.1-22,107.4-33.2,164.6-33.2c57.1,0,112.5,11.2,164.6,33.2c50.3,21.3,95.6,51.8,134.4,90.6c38.8,38.9,69.3,84.1,90.6,134.4c22,52.1,33.2,107.4,33.2,164.6c0,57.1-11.2,112.5-33.2,164.6C868.3,714.9,837.8,760.1,799,799L799,799z M727.6,315.4L426.9,616.2L297,486.3c-12.6-12.6-33-12.6-45.6,0c-12.6,12.6-12.6,33,0,45.6l152.6,152.6c12.6,12.6,33,12.6,45.6,0L773.2,361c12.6-12.6,12.6-33,0-45.6C760.6,302.8,740.2,302.8,727.6,315.4L727.6,315.4z"/></g>
</svg>
    `));
}

Promise.all(promises).then(() => {
  console.log('Rendered', promises.length, 'images');
}).catch((err) => {
  console.error(err);
});
```

Please tell me your thought. I will close this for now and would reopen if there is still any issue. 😄 

Jason

**Closed as completed by ycmjason** 2018-11-23 15:45 UTC
